/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateria;

import conexion.conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belen
 */
public class FrmMenu extends javax.swing.JFrame {

    

    public FrmMenu() {
        initComponents();
        ConfigForm();
    }

    public final void ConfigForm() {
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0));
        this.setBackground(new Color(0, 0, 0));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProducto = new javax.swing.JMenu();
        Menu_Altas = new javax.swing.JMenuItem();
        Menu_Inventario = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenu();
        ItemReporteGlobal = new javax.swing.JMenuItem();
        ItemReporteDia = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        ItemRealizarVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú Administrador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(220, 230, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("W:\\Documentos\\NetBeansProjects\\Zapateria\\Sin título.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 321, 280);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 321, 280));

        menuProducto.setForeground(new java.awt.Color(255, 102, 0));
        menuProducto.setText("Producto");
        menuProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Menu_Altas.setBackground(new java.awt.Color(255, 0, 0));
        Menu_Altas.setText("Altas");
        Menu_Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_AltasActionPerformed(evt);
            }
        });
        menuProducto.add(Menu_Altas);

        Menu_Inventario.setBackground(new java.awt.Color(255, 0, 0));
        Menu_Inventario.setText("Inventario");
        Menu_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_InventarioActionPerformed(evt);
            }
        });
        menuProducto.add(Menu_Inventario);

        jMenuBar1.add(menuProducto);

        menuReporte.setForeground(new java.awt.Color(255, 102, 0));
        menuReporte.setText("Reportes");
        menuReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ItemReporteGlobal.setText("Reporte Global");
        ItemReporteGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemReporteGlobalActionPerformed(evt);
            }
        });
        menuReporte.add(ItemReporteGlobal);

        ItemReporteDia.setText("Reporte por día");
        ItemReporteDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemReporteDiaActionPerformed(evt);
            }
        });
        menuReporte.add(ItemReporteDia);

        jMenuBar1.add(menuReporte);

        menuVenta.setForeground(new java.awt.Color(255, 102, 0));
        menuVenta.setText("Ventas");
        menuVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ItemRealizarVenta.setText("Realizar Venta");
        ItemRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRealizarVentaActionPerformed(evt);
            }
        });
        menuVenta.add(ItemRealizarVenta);

        jMenuBar1.add(menuVenta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_AltasActionPerformed
        new frmAltas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_AltasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void ItemReporteGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemReporteGlobalActionPerformed
        new FrmReporteGlobal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemReporteGlobalActionPerformed

    private void ItemReporteDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemReporteDiaActionPerformed
        new FrmReportes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemReporteDiaActionPerformed

    private void ItemRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRealizarVentaActionPerformed
        new FrmVentas1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemRealizarVentaActionPerformed

    private void Menu_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_InventarioActionPerformed
        new FrmInventario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_InventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemRealizarVenta;
    private javax.swing.JMenuItem ItemReporteDia;
    private javax.swing.JMenuItem ItemReporteGlobal;
    private javax.swing.JMenuItem Menu_Altas;
    private javax.swing.JMenuItem Menu_Inventario;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
