/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateria;

import Utilidades.Fecha;
import conexion.conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belen
 */
public class FrmReporteGlobal extends javax.swing.JFrame {

    conexion con = new conexion();
    Connection cn = con.conexion();
    ReporteGlobal ticket = new ReporteGlobal();
    Fecha fecha = new Fecha();

    DefaultTableModel llenar;
    ArrayList<VentasVo> ven = new ArrayList<>();
    ArrayList<ReporteVo> rep = new ArrayList<>();

    public FrmReporteGlobal() {
        initComponents();
        configForm();
    }

    private void configForm() {
        llenar = (DefaultTableModel) TablaTodasLasVentas.getModel();
        llenarT();
        suma();
        FrmReporteGlobal.this.getRootPane().setOpaque(false);
        FrmReporteGlobal.this.getContentPane().setBackground(new Color(102, 102, 102));
        FrmReporteGlobal.this.setBackground(new Color(102, 102, 102));
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    public void llenarT() {
        try {
            LimpiarTabla();
            Statement st = con.conexion().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM vntprod");
            while (rs.next()) {
                Object[] dat = new Object[6];
                dat[0] = rs.getInt(1);//id
                dat[1] = rs.getString(2);//producto
                dat[2] = rs.getInt(3);//codigo
                dat[3] = rs.getString(4);//precio
                dat[4] = rs.getInt(5);//cantidad
                dat[5] = rs.getInt(6);//total
                llenar.addRow(dat);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void LimpiarTabla() {
        for (int i = TablaTodasLasVentas.getRowCount() - 1; i >= 0; i--) {
            llenar.removeRow(i);
        }
    }

    private void suma() {
        txtGanancias.setText("0");
        txtTotalDeParesVendidos.setText("0");
        int ta = llenar.getRowCount();
        int c = 0;
        do {
            try {
                int f = c++;
                int totales = Integer.parseInt(llenar.getValueAt(f, 5).toString());
                String ganancias = txtGanancias.getText();
                int nu2 = Integer.parseInt(ganancias);
                long re = totales + nu2;

                int par = Integer.parseInt(llenar.getValueAt(f, 4).toString());
                String pares = txtTotalDeParesVendidos.getText();
                int nu = Integer.parseInt(pares);
                long ParesVendidos = par + nu;

                txtGanancias.setText(String.valueOf(re));
                txtTotalDeVentas.setText(String.valueOf(f + 1));
                txtTotalDeParesVendidos.setText(String.valueOf(ParesVendidos));

            } catch (NumberFormatException e) {
                System.out.println(e);
            }

        } while (c < ta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTodasLasVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotalDeVentas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGanancias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalDeParesVendidos = new javax.swing.JTextField();
        btnCrearPDF = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reporte Global");
        setBackground(new java.awt.Color(153, 0, 153));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Todas las ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        jScrollPane1.setOpaque(false);

        TablaTodasLasVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_ventas", "Producto", "Código", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(TablaTodasLasVentas);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Total de ventas:");

        txtTotalDeVentas.setEditable(false);
        txtTotalDeVentas.setBackground(new java.awt.Color(255, 255, 204));
        txtTotalDeVentas.setForeground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Ganancias:");

        txtGanancias.setEditable(false);
        txtGanancias.setBackground(new java.awt.Color(255, 255, 204));
        txtGanancias.setForeground(new java.awt.Color(102, 0, 102));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Total de pares vendidos:");

        txtTotalDeParesVendidos.setEditable(false);
        txtTotalDeParesVendidos.setBackground(new java.awt.Color(255, 255, 204));
        txtTotalDeParesVendidos.setForeground(new java.awt.Color(102, 0, 102));

        btnCrearPDF.setBackground(new java.awt.Color(255, 204, 204));
        btnCrearPDF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearPDF.setText("Crear PDF");
        btnCrearPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPDFActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalDeParesVendidos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGanancias)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearPDF)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTotalDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTotalDeParesVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegresar)
                        .addComponent(btnCrearPDF)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPDFActionPerformed
        VentasVo ventaprod;
        for (int i = 0; i < TablaTodasLasVentas.getRowCount(); i++) {
            ventaprod = new VentasVo();
            ventaprod.setId(Integer.parseInt(TablaTodasLasVentas.getValueAt(i, 0).toString()));
            ventaprod.setNombre(TablaTodasLasVentas.getValueAt(i, 1).toString());
            ventaprod.setCodigo(Integer.parseInt(TablaTodasLasVentas.getValueAt(i, 2).toString()));
            ventaprod.setPrecio(Integer.parseInt(TablaTodasLasVentas.getValueAt(i, 3).toString()));
            ventaprod.setCantidad(Integer.parseInt(TablaTodasLasVentas.getValueAt(i, 4).toString()));
            ventaprod.setTotal(Integer.parseInt(TablaTodasLasVentas.getValueAt(i, 5).toString()));
            ven.add(ventaprod);
        }

        //generar ticket
        ReporteVo datos = new ReporteVo();
        datos.setGanancias(Integer.parseInt(txtGanancias.getText()));
        datos.setTotalVentas(Integer.parseInt(txtTotalDeVentas.getText()));
        datos.setParesVendidos(Integer.parseInt(txtTotalDeParesVendidos.getText()));
        rep.add(datos);

        String f = fecha.getMesActual() + fecha.getHora() + fecha.getMinuto();
        ticket.generarTicket((f), datos,ven);
    }//GEN-LAST:event_btnCrearPDFActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReporteGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReporteGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReporteGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReporteGlobal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReporteGlobal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTodasLasVentas;
    private javax.swing.JButton btnCrearPDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGanancias;
    private javax.swing.JTextField txtTotalDeParesVendidos;
    private javax.swing.JTextField txtTotalDeVentas;
    // End of variables declaration//GEN-END:variables
}
